# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/linh9/Desktop/dc11m_27_3/zybo_z7.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_encoder_0_0/design_1_encoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_encoder_0_0 || ORIG_REF_NAME==design_1_encoder_0_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_ADC_0_0/design_1_ADC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ADC_0_0 || ORIG_REF_NAME==design_1_ADC_0_0}]

# IP: bd/design_1/ip/design_1_fix_clk_i_w_0_0/design_1_fix_clk_i_w_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fix_clk_i_w_0_0 || ORIG_REF_NAME==design_1_fix_clk_i_w_0_0}]

# IP: bd/design_1/ip/design_1_input_ctrl_0_0/design_1_input_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_input_ctrl_0_0 || ORIG_REF_NAME==design_1_input_ctrl_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: bd/design_1/ip/design_1_ab2alphabeta_0_0/design_1_ab2alphabeta_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ab2alphabeta_0_0 || ORIG_REF_NAME==design_1_ab2alphabeta_0_0}]

# IP: bd/design_1/ip/design_1_datalimit_0_0/design_1_datalimit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_datalimit_0_0 || ORIG_REF_NAME==design_1_datalimit_0_0}]

# IP: bd/design_1/ip/design_1_srcClk_0_0/design_1_srcClk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_srcClk_0_0 || ORIG_REF_NAME==design_1_srcClk_0_0}]

# IP: bd/design_1/ip/design_1_usample_0_0/design_1_usample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_0_0 || ORIG_REF_NAME==design_1_usample_0_0}]

# IP: bd/design_1/ip/design_1_usample_1_0/design_1_usample_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_1_0 || ORIG_REF_NAME==design_1_usample_1_0}]

# IP: bd/design_1/ip/design_1_usample_2_0/design_1_usample_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_2_0 || ORIG_REF_NAME==design_1_usample_2_0}]

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0}]

# IP: bd/design_1/ip/design_1_SwitchCOntroller_0_0/design_1_SwitchCOntroller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SwitchCOntroller_0_0 || ORIG_REF_NAME==design_1_SwitchCOntroller_0_0}]

# IP: bd/design_1/ip/design_1_protect_van_0_0/design_1_protect_van_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_protect_van_0_0 || ORIG_REF_NAME==design_1_protect_van_0_0}]

# IP: bd/design_1/ip/design_1_ila_1_0/design_1_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_1_0 || ORIG_REF_NAME==design_1_ila_1_0}]

# IP: bd/design_1/ip/design_1_datalimit_1_0/design_1_datalimit_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_datalimit_1_0 || ORIG_REF_NAME==design_1_datalimit_1_0}]

# IP: bd/design_1/ip/design_1_Controler_0_0/design_1_Controler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Controler_0_0 || ORIG_REF_NAME==design_1_Controler_0_0}]

# IP: bd/design_1/ip/design_1_usample_3_0/design_1_usample_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_3_0 || ORIG_REF_NAME==design_1_usample_3_0}]

# IP: bd/design_1/ip/design_1_usample_4_0/design_1_usample_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_4_0 || ORIG_REF_NAME==design_1_usample_4_0}]

# IP: bd/design_1/ip/design_1_usample_5_0/design_1_usample_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_5_0 || ORIG_REF_NAME==design_1_usample_5_0}]

# IP: bd/design_1/ip/design_1_usample_6_0/design_1_usample_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_6_0 || ORIG_REF_NAME==design_1_usample_6_0}]

# IP: bd/design_1/ip/design_1_usample_7_0/design_1_usample_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usample_7_0 || ORIG_REF_NAME==design_1_usample_7_0}]

# XDC: bd/design_1/design_1_ooc.xdc
