# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/linh9/Desktop/src/dc11m/test_dodong/test_dodong.cache/wt [current_project]
set_property parent.project_path C:/Users/linh9/Desktop/src/dc11m/test_dodong/test_dodong.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/linh9/Desktop/src/dc11m/test_dodong/test_dodong.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/linh9/Desktop/src/do_dong/ADC.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ADC -part xc7z020clg400-1


write_checkpoint -force -noxdef ADC.dcp

catch { report_utilization -file ADC_utilization_synth.rpt -pb ADC_utilization_synth.pb }
