# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/linh9/Desktop/src/test_ctrl/test_ctrl.cache/wt [current_project]
set_property parent.project_path C:/Users/linh9/Desktop/src/test_ctrl/test_ctrl.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/linh9/Desktop/src/test_ctrl/test_ctrl.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/linh9/Desktop/src/MPC/mpc_vecto_kg.vhd
  C:/Users/linh9/Desktop/src/MPC/mpc_iabk1.vhd
  C:/Users/linh9/Desktop/src/MPC/mpc_Ciab.vhd
  C:/Users/linh9/Desktop/src/MPC/vector_lien_ke.vhd
  C:/Users/linh9/Desktop/src/MPC/OpCostFunction.vhd
  C:/Users/linh9/Desktop/src/MPC/mpc_select_Vk1.vhd
  C:/Users/linh9/Desktop/src/MPC/mpc_sample.vhd
  C:/Users/linh9/Desktop/src/MPC/mpc_predic_ik1.vhd
  C:/Users/linh9/Desktop/src/MPC/Mpc_PredicIk2.vhd
  C:/Users/linh9/Desktop/src/MHTT/sincoslut.vhd
  C:/Users/linh9/Desktop/src/MHTT/MHTT.vhd
  C:/Users/linh9/Desktop/src/MHTT/fm_sample.vhd
  C:/Users/linh9/Desktop/src/MHTT/d2ab.vhd
  C:/Users/linh9/Desktop/src/MHTT/ab2dq.vhd
  C:/Users/linh9/Desktop/src/srcCLk.vhd
  C:/Users/linh9/Desktop/src/test_ctrl/test_ctrl.srcs/sources_1/new/sampleIref.vhd
  C:/Users/linh9/Desktop/src/PI.vhd
  C:/Users/linh9/Desktop/src/MPC/mpc.vhd
  C:/Users/linh9/Desktop/src/dq2ab.vhd
  C:/Users/linh9/Desktop/src/MHTT/FluxModule.vhd
  C:/Users/linh9/Desktop/src/Controller.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Controler -part xc7z020clg400-1


write_checkpoint -force -noxdef Controler.dcp

catch { report_utilization -file Controler_utilization_synth.rpt -pb Controler_utilization_synth.pb }
